# Generated by Django 4.2.5 on 2023-09-25 12:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=30)),
                ('uemail', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project_roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ManyToManyField(to='docapp.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docapp.user'),
        ),
    ]
