# Generated by Django 4.2.5 on 2023-09-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_roles',
            new_name='Project_role',
        ),
    ]
