# Generated by Django 4.2.5 on 2023-09-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0002_rename_project_roles_project_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_role',
            name='role',
            field=models.CharField(choices=[('O', 'Owner'), ('A', 'Admin'), ('K', 'Add docs'), ('E', 'Edit docs'), ('C', 'Comment'), ('R', 'Read')], default='R', max_length=1),
        ),
    ]
